In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8418, 4403, 1437, 4211],
 [8418, 4403, 1437, 7000],
 [8418, 6629, 1437, 918],
 [1707, 4347, 9457, 7764, 1610],
 [1707, 4347, 9457, 7764, 7414],
 [9053, 8418, 462, 1437, 8109],
 [68, 1443, 7092, 7764]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8418 4403 1437 4211]
 [   0    0    0    0 8418 4403 1437 7000]
 [   0    0    0    0 8418 6629 1437  918]
 [   0    0    0 1707 4347 9457 7764 1610]
 [   0    0    0 1707 4347 9457 7764 7414]
 [   0    0    0 9053 8418  462 1437 8109]
 [   0    0    0    0   68 1443 7092 7764]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\anjal\Deep_Learning_NLP\venvac\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:

model.build(input_shape=(None, sent_length))
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 787ms/step


array([[[ 3.12931798e-02, -2.15785392e-02,  1.22310519e-02,
         -3.01797520e-02, -3.95803079e-02, -4.73208204e-02,
         -2.21507680e-02, -4.61468101e-02, -4.11431082e-02,
          2.62919925e-02],
        [ 3.12931798e-02, -2.15785392e-02,  1.22310519e-02,
         -3.01797520e-02, -3.95803079e-02, -4.73208204e-02,
         -2.21507680e-02, -4.61468101e-02, -4.11431082e-02,
          2.62919925e-02],
        [ 3.12931798e-02, -2.15785392e-02,  1.22310519e-02,
         -3.01797520e-02, -3.95803079e-02, -4.73208204e-02,
         -2.21507680e-02, -4.61468101e-02, -4.11431082e-02,
          2.62919925e-02],
        [ 3.12931798e-02, -2.15785392e-02,  1.22310519e-02,
         -3.01797520e-02, -3.95803079e-02, -4.73208204e-02,
         -2.21507680e-02, -4.61468101e-02, -4.11431082e-02,
          2.62919925e-02],
        [ 4.62015718e-03,  2.41266564e-03,  9.39167663e-03,
          3.41132022e-02,  2.94993855e-02, -4.70415466e-02,
          3.21865082e-05, -9.80073214e-03, -1.359089

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8418, 4403, 1437, 4211], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>